In [1]:
import numpy as np
from numpy.linalg import matrix_power

In [2]:
T = np.array([
    [.92,.12],
    [.08,.88],
])

In [11]:
S0 = np.array([
    [24500],
    [45200]
])

In [4]:
T @ P0

array([[27964.],
       [41736.]])

In [16]:
Tn = matrix_power(T,49)
Tn

array([[0.44444444, 0.44444444],
       [0.55555556, 0.55555556]])

In [12]:
TN = np.array([
    [.6,.6],
    [.4,.4]
])

In [13]:
TN @ S0

array([[41820.],
       [27880.]])